package com.esewa.javabackend.controller;

import com.esewa.javabackend.dto.InteractionDTO;
import com.esewa.javabackend.dto.RecipeDTO;
import com.esewa.javabackend.dto.UserDTO.FollowDTO;
import com.esewa.javabackend.dto.UserDTO.UserResponseDTO;
import com.esewa.javabackend.dto.aiml.AIMLDataDTO;
import com.esewa.javabackend.dto.postDTO.PostResponseDTO;
import com.esewa.javabackend.service.*;
import com.esewa.javabackend.service.AIML.AIMLService;
import com.esewa.javabackend.service.AIML.DatasetImportService;
import com.esewa.javabackend.service.AIML.EmbeddingService;
import com.esewa.javabackend.service.AIML.InteractionService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.Map;

@RestController
@RequestMapping("/api/aiml")
@RequiredArgsConstructor
@Slf4j
public class AIMLDataController {

    private final UserService userService;
    private final PostService postService;
    private final RecipeService recipeService;
    private final InteractionService interactionService;
    private final FollowService followService;
    private final EmbeddingService embeddingService;
    private final DatasetImportService datasetImportService;
    private final AIMLService aimlService;

    /**
     * Get complete dataset for ML training
     * Returns all users, posts, recipes, interactions, follows, and embeddings
     */
    @GetMapping("/dataset")
    public ResponseEntity<AIMLDataDTO> getFullDataset() {

        AIMLDataDTO dataset = AIMLDataDTO.builder()
                .users(userService.getAllUsers().stream()
                        .filter(UserResponseDTO::isNew)
                        .toList())
                .posts(postService.fetchAllPosts().stream()
                        .filter(PostResponseDTO::isNew)
                        .toList())
                .recipes(recipeService.findAllRecipes().stream()
                        .filter(RecipeDTO::isNew)
                        .toList())
                .interactions(interactionService.allInteraction().stream()
                        .filter(InteractionDTO::isNew)
                        .toList())
                .follows(followService.getAllFollows().stream()
                        .filter(FollowDTO::isNew)
                        .toList())
                .embeddings(embeddingService.getAllEmbeddings())
                .build();

        aimlService.markDatasetAsTrained(dataset);

        return ResponseEntity.ok(dataset);
    }

    /**
     * Import ML dataset from uploaded JSON file
     * Accepts a JSON file generated by the Python dataset generator
     * 
     * @param file The JSON file containing the dataset
     * @return Import statistics including number of records imported
     */
    @PostMapping(value = "/dataset/import", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public ResponseEntity<Map<String, Object>> importDataset(@RequestParam("file") MultipartFile file) {
        log.info("Received dataset import request: {}", file.getOriginalFilename());

        try {
            if (file.isEmpty()) {
                return ResponseEntity.badRequest()
                        .body(Map.of("success", false, "error", "File is empty"));
            }

            if (!file.getOriginalFilename().endsWith(".json")) {
                return ResponseEntity.badRequest()
                        .body(Map.of("success", false, "error", "File must be JSON format"));
            }

            Map<String, Object> stats = datasetImportService.importDatasetFromUpload(file);

            if ((Boolean) stats.get("success")) {
                log.info("Dataset import completed successfully");
                return ResponseEntity.ok(stats);
            } else {
                log.error("Dataset import failed: {}", stats.get("error"));
                return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(stats);
            }

        } catch (Exception e) {
            log.error("Error importing dataset", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of(
                            "success", false,
                            "error", e.getMessage()));
        }
    }

    /**
     * Import ML dataset from JSON string
     * Useful for programmatic imports or small datasets
     * 
     * @param jsonData The JSON string containing the dataset
     * @return Import statistics
     */
    @PostMapping(value = "/dataset/import-json", consumes = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map<String, Object>> importDatasetJson(@RequestBody String jsonData) {
        log.info("Received dataset import request from JSON string");

        try {
            Map<String, Object> stats = datasetImportService.importDatasetFromString(jsonData);

            if ((Boolean) stats.get("success")) {
                log.info("Dataset import completed successfully");
                return ResponseEntity.ok(stats);
            } else {
                log.error("Dataset import failed: {}", stats.get("error"));
                return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(stats);
            }

        } catch (Exception e) {
            log.error("Error importing dataset", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of(
                            "success", false,
                            "error", e.getMessage()));
        }
    }

    /**
     * Get current dataset statistics
     * Returns counts of all entities in the database
     */
    @GetMapping("/dataset/stats")
    public ResponseEntity<Map<String, Long>> getDatasetStatistics() {
        log.info("Fetching dataset statistics");
        return ResponseEntity.ok(datasetImportService.getDatasetStatistics());
    }

    /**
     * Clear all ML data from database
     * WARNING: This will delete all users, recipes, posts, interactions, follows,
     * and embeddings
     * Use with extreme caution!
     */
    @DeleteMapping("/dataset/clear")
    public ResponseEntity<Map<String, String>> clearDataset() {
        log.warn("Received request to clear all dataset");

        try {
            datasetImportService.clearAllData();
            return ResponseEntity.ok(Map.of(
                    "success", "true",
                    "message", "All dataset cleared successfully"));
        } catch (Exception e) {
            log.error("Error clearing dataset", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of(
                            "success", "false",
                            "error", e.getMessage()));
        }
    }
}
